[tool.poetry]
name = "slack-notifier"
version = "0.1.0"
description = ""
authors = ["Sigurd Ljødal <sigurd.ljodal@kolonial.no>"]
license = "MIT"
packages = [
    { include = "notifier" },
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "0.16.1"
dacite = "^1.6.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "20.8b1"
isort = "^5.1.4"
mypy = "0.790"
flake8-bugbear = "^20.11.1"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
